# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0146_auto_20160909_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trumpify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.PositiveIntegerField()),
                ('tweet', models.CharField(max_length=256)),
                ('result', models.CharField(max_length=512, null=True)),
                ('worker_id', models.PositiveIntegerField()),
                ('task_created_at', models.DateTimeField()),
                ('task_worker_created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='crowdsourcing.Trumpify'),
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_picked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_as_answer', to='crowdsourcing.Trumpify'),
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Trumpify'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tweet_picked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_as_tweet', to='crowdsourcing.Trumpify'),
        ),
    ]
