language: python

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

branches:
  only:
    - develop2

python:
  - "2.7"

# command to install dependencies
install:
    travis_wait pip install -r requirements.txt;
    pip install flake8

before_script:
    flake8 .

# command to run tests
script: python manage.py test
